### ISSUE TITLE
"cwsca" ist bei "/status"-Abfragen konstant... 

### ISSUE THREAD

**Issue by chk2902** [goecharger/go-eCharger-API-v2#11]
Ich hätte einen stetig verändernden Wert erwartet.

**Comment by peterpoetzi** [comment]
Man kann cwsca (cloud web socket connected age) von rbt (reboot time) abziehen um herauszufinden wie lange die Cloud schon verbunden ist, sprich cwsca ist der Zeitpunkt wann die Cloud Verbindung hergestellt wurde.

**Comment by chk2902** [comment]
Klappt, danke.
