### ISSUE TITLE
AMX in API v2 not available anymore?

### ISSUE THREAD

**Issue by IPSCoyote** [goecharger/go-eCharger-API-v2#112]
Hi,

I till now used the API v1 where it was mentioned to use "amx" to set the charging amperage as this is not effecting the Flash memory.
This key seems not to be present anymore with API v2. Shall we use then "amp" again?

regs

**Comment by 0xFEEDC0DE64** [comment]
Just use amp, we do not have any limitations anymore with eeprom write cycles anymore (I introduced nvs with flash wear leveling 2 years ago starting with V3 chargers)
