### ISSUE TITLE
trx schreiben: Verhalten anders als Dokumentation

### ISSUE THREAD

**Issue by 4homeassistant** [goecharger/go-eCharger-API-v2#116]
Wie ist denn hier der aktuelle Stand und das gewollte Verhalten. Entgegen der API-Doku in https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-de.md lässt sich nur `null` oder `0` setzen, nicht aber der cardIndex wie beschrieben.
![image](https://user-images.githubusercontent.com/117555636/215903670-4135dac3-2cf1-44e8-866d-516001fb6aab.png)

Der nette Support-Kollege hat mir dazu geschrieben:
_"trx lässt sich im Moment tatsächlich nur mit 0 setzen, auch das ist ein gewolltes Verhalten.
Hier habe ich allerdings tatsächlich noch gar keine Information darüber ob geplant ist dies in Zukunft auch mit den RFID-Konten beschreibbar zu machen. Gerne frage ich in unserer Entwicklung dafür nach."_

**Comment by 0xFEEDC0DE64** [comment]
mit der neuesten beta firmware sollte auch trx=1 usw gehen

**Comment by 4homeassistant** [comment]
Super, danke Dir @0xFEEDC0DE64. Das macht die Sache rund. Weißt Du ab wann die Beta Firmware verfügbar ist? Bei unseren Chargern sehe ich sie noch nicht.

**Comment by 4homeassistant** [comment]
@0xFEEDC0DE64, ich habe die neue Beta gestern auf unseren Chargern installiert und die Funktion testen können. Es funktioniert jetzt, wie in der Doku beschrieben. Eine Anregung hätte ich aber noch: sofern kein Fahrzeug verbunden ist, stellt sich `trx` - egal ob via RFID oder API gesetzt nach 120 Sekunden wieder auf `null` zurück. Könnt Ihr diesen Timer etwas großzügiger auslegen und dieses Verhalten auch dokumentieren? Für den gewöhnlichen Vorgang 1) Kabel zum jeweiligen Auto ziehen, 2) Ladeport öffnen und 3) Stecker einstecken ist diese Zeit knapp bemessen. Wir haben bisher immer nach der Ursache gesucht und nun während des Testens dieses Verhalten nachvollziehen können.

**Comment by 0xFEEDC0DE64** [comment]
konnte den bug in der api key implementierung trx finden und beheben, beim nächsten firmware update ist das dabei!

**Comment by 0xFEEDC0DE64** [comment]
sollte nun seit dem heutigen firmware relase 055.6 gefixt sein

**Comment by 4homeassistant** [comment]
Vielen lieben Dank Daniel @0xFEEDC0DE64
Gerade alle upgedatet und erfolgreich gecheckt.
