### ISSUE TITLE
trx setzen: falscher Wert wird übernommen (-1)

### ISSUE THREAD

**Issue by 4homeassistant** [goecharger/go-eCharger-API-v2#124]
Wenn ich ```trx``` setzte wird immer ein um 1 niedrigerer Wert übernommen. Setze ich beispielsweise ```trx``` auf ```1``` wird ```0``` übernommen. Das Verhalten tritt sowohl über MQTT als auch über die lokale http-API auf.

```
http://xxx.xxx.xxx.xxx/api/set?trx=1
{"trx":true}

http://xxx.xxx.xxx.xxx/api/status?filter=trx
{"trx":0}
```

**Comment by 0xFEEDC0DE64** [comment]
0 wird für die app verwendet, 1-10 für die 10 rfid karten

**Comment by 4homeassistant** [comment]
Ja richtig Daniel. Lässt sich auf unseren beiden Chargern beliebig reproduzieren. Auf beiden läuft aktuell die 055.5 Beta. Das Verhalten besteht aber seit der 055.0.

**Comment by 0xFEEDC0DE64** [comment]
konnte den bug in der api key implementierung finden und beheben, beim nächsten firmware update ist das dabei!

**Comment by 4homeassistant** [comment]
Top! Danke Daniel 😊
