### ISSUE TITLE
Go-e Charger rejects OCPP connection from EVCC

### ISSUE THREAD

**Issue by ChandlerWatt** [goecharger/go-eCharger-API-v2#126]
Hello,

I have connected a Go-e Charger via OCPP to [EVCC](https://github.com/evcc-io/evcc) on Linux, but the Go-e charger rejects the connection every time.

How to reproduce:
- Connected a Go-e Charger via OCPP to EVCC
- Restart the Go-e charger to initialize the connection process
- The logs should show something similar to this:
`received JSON message from go-eCharger_205643: [3,"4103645269",{"status":"Rejected"}]`

I also attached the complete log file: [OCPP.log](https://github.com/goecharger/go-eCharger-API-v2/files/11049993/OCPP.log)

**Comment by 0xFEEDC0DE64** [comment]
it would help if we could add custom error messages to the rejected response, where I could write why I rejected something. But I am not sure if this would break the ocpp protocol.

What we can do now is you write a message to our support and tell them your serial number and ask for our OCPP remote debugging to be enabled, then I can see the reason for the reject message. Maybe we have to fix something in the ocpp implementation...

you can also send your serial number to my email adress

**Comment by andig** [comment]
@0xFEEDC0DE64 if I can help from evcc side let me know. We can always run an Ocpp Server if you want to connect against.

**Comment by 0xFEEDC0DE64** [comment]
ok sure if you provide me with a ocpp url, i will connect

**Comment by andig** [comment]
Could you contact info@evcc.io? Would need to do this over the weekend...

**Comment by ChristophWatt** [comment]
Anything I can help with or is it better to not involve to many?

**Comment by thomas-hutterer-tik** [comment]
Hi @0xFEEDC0DE64 please call me on 0699 18790722. I would love to get this resolved and I am at the location now where I can test the charger. Thanks Thomas

**Comment by 0xFEEDC0DE64** [comment]
sure, give me another hour or so, then I will call

**Comment by andig** [comment]
You can also call me if necessary, @thomas-hutterer-tik has the details

**Comment by 0xFEEDC0DE64** [comment]
the firmware had a bug, that if the meter values buffer was empty it could not send the meter values. I changed the behaviour so that on request, we send a single meter values entry and do not change the interval of normally sent meter values (MeterValueSampleInterval and ClockAlignedDataInterval). We will test the new firmware with evcc soon

**Comment by 0xFEEDC0DE64** [comment]
Check out the new beta firmware release 055.6, it has been released!

**Comment by slev1n** [comment]
Hi @0xFEEDC0DE64 ,
i also get "Rejected" if evcc want to change the state:
`Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] INFO 2023/07/02 22:27:40 chargepoint connected, registering: goe123456
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 sent JSON message to goe123456: [2,"3526263417","GetConfiguration",{}]
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 received JSON message from goe123456: [3,"3526263417",{"configurationKey":[{"key":"AllowOfflineTxForUnknownId","readonly":false,"value":"false"},{"key":"GetConfigurationMaxKeys","readonly":true,"value":"99"},{"key":"ClockAlignedDataInterval","readonly":false,"value":"0"},{"key":"LocalAuthorizeOffline","readonly":false,"value":"true"},{"key":"HeartbeatInterval","readonly":false,"value":"60"},{"key":"LightIntensity","readonly":false,"value":"17"},{"key":"MeterValuesSampledData","readonly":true,"value":"Current.Import,Current.Offered,Energy.Active.Import.Register,Frequency,Power.Active.Import,Power.Factor,Power.Offered,Temperature,Voltage"},{"key":"MeterValuesSampledDataMaxLength","readonly":true,"value":"10"},{"key":"MeterValueSampleInterval","readonly":false,"value":"180"},{"key":"NumberOfConnectors","readonly":true,"value":"1"},{"key":"ConnectorPhaseRotation","readonly":true,"value":"0.RST,1.RST"},{"key":"ConnectorPhaseRotationMaxLength","readonly":true,"value":"3"},{"key":"SupportedFeatureProfiles","readonly":true,"value":"Core,FirmwareManagement,SmartCharging,RemoteTrigger"},{"key":"SupportedFeatureProfilesMaxLength","readonly":true,"value":"6"},{"key":"UnlockConnectorOnEVSideDisconnect","readonly":false,"value":"true"},{"key":"WebSocketPingInterval","readonly":false,"value":"10"},{"key":"LocalAuthListEnabled","readonly":false,"value":"true"},{"key":"LocalAuthListMaxLength","readonly":true,"value":"10"},{"key":"SendLocalListMaxLength","readonly":true,"value":"10"},{"key":"ChargeProfileMaxStackLevel","readonly":true,"value":"20"},{"key":"ChargingScheduleAllowedChargingRateUnit","readonly":true,"value":"Current"},{"key":"ChargingScheduleMaxPeriods","readonly":true,"value":"20"},{"key":"ConnectorSwitch3to1PhaseSupported","readonly":true,"value":"true"},{"key":"MaxChargingProfilesInstalled","readonly":true,"value":"20"},{"key":"AccessControl","readonly":true,"value":"Open"}]}]
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 AccessControl (r/o): Open
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 AllowOfflineTxForUnknownId (r/w): false
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 ChargeProfileMaxStackLevel (r/o): 20
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 ChargingScheduleAllowedChargingRateUnit (r/o): Current
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 ChargingScheduleMaxPeriods (r/o): 20
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 ClockAlignedDataInterval (r/w): 0
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 ConnectorPhaseRotation (r/o): 0.RST,1.RST
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 ConnectorPhaseRotationMaxLength (r/o): 3
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 ConnectorSwitch3to1PhaseSupported (r/o): true
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 GetConfigurationMaxKeys (r/o): 99
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 HeartbeatInterval (r/w): 60
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 LightIntensity (r/w): 17
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 LocalAuthListEnabled (r/w): true
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 LocalAuthListMaxLength (r/o): 10
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 LocalAuthorizeOffline (r/w): true
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 MaxChargingProfilesInstalled (r/o): 20
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 MeterValueSampleInterval (r/w): 180
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 MeterValuesSampledData (r/o): Current.Import,Current.Offered,Energy.Active.Import.Register,Frequency,Power.Active.Import,Power.Factor,Power.Offered,Temperature,Voltage
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 MeterValuesSampledDataMaxLength (r/o): 10
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 NumberOfConnectors (r/o): 1
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 SendLocalListMaxLength (r/o): 10
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 SupportedFeatureProfiles (r/o): Core,FirmwareManagement,SmartCharging,RemoteTrigger
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 SupportedFeatureProfilesMaxLength (r/o): 6
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 UnlockConnectorOnEVSideDisconnect (r/w): true
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 WebSocketPingInterval (r/w): 10
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 sent JSON message to goe123456: [2,"1612164215","TriggerMessage",{"requestedMessage":"MeterValues","connectorId":1}]
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 received JSON message from goe123456: [2,"531531541","BootNotification",{"chargePointVendor":"go-e","chargePointModel":"go-eCharger_V4","chargePointSerialNumber":"209225","firmwareVersion":"055.7"}]
Jul  2 22:27:40 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:40 sent JSON message to goe123456: [3,"531531541",{"currentTime":"2023-07-02T20:27:40Z","interval":60,"status":"Accepted"}]
Jul  2 22:27:41 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:41 received JSON message from goe123456: [3,"1612164215",{"status":"Accepted"}]
Jul  2 22:27:41 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:41 TriggerMessage MeterValues for goe123456: Accepted
Jul  2 22:27:41 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:41 received JSON message from goe123456: [2,"531531542","MeterValues",{"connectorId":1,"meterValue":[{"timestamp":"2023-07-02T20:27:40.908Z","sampledValue":[{"value":"0.00","measurand":"Current.Import","unit":"A","phase":"L1"},{"value":"0.00","measurand":"Current.Import","unit":"A","phase":"L2"},{"value":"0.00","measurand":"Current.Import","unit":"A","phase":"L3"},{"value":"165333.00","measurand":"Energy.Active.Import.Register","unit":"Wh"},{"value":"0.00","measurand":"Power.Active.Import","unit":"W","phase":"L1"},{"value":"0.00","measurand":"Power.Active.Import","unit":"W","phase":"L2"},{"value":"0.00","measurand":"Power.Active.Import","unit":"W","phase":"L3"},{"value":"0.00","measurand":"Power.Active.Import","unit":"W"}]}]}]
Jul  2 22:27:41 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:41 sent JSON message to goe123456: [3,"531531542",{}]
Jul  2 22:27:41 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:41 received JSON message from goe123456: [2,"531531543","StatusNotification",{"connectorId":0,"errorCode":"NoError","status":"Available","timestamp":"2023-07-02T20:27:41.005Z"}]
Jul  2 22:27:41 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:41 sent JSON message to goe123456: [3,"531531543",{}]
Jul  2 22:27:41 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:41 received JSON message from goe123456: [2,"531531544","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"SuspendedEVSE","timestamp":"2023-07-02T20:27:41.005Z"}]
Jul  2 22:27:41 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:27:41 sent JSON message to goe123456: [3,"531531544",{}]
Jul  2 22:28:00 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:28:00 sent JSON message to goe123456: [2,"2558598256","RemoteStartTransaction",{"connectorId":1,"idTag":"evcc","chargingProfile":{"chargingProfileId":1,"stackLevel":0,"chargingProfilePurpose":"TxProfile","chargingProfileKind":"Relative","chargingSchedule":{"chargingRateUnit":"A","chargingSchedulePeriod":[{"startPeriod":0,"limit":16}]}}}]
Jul  2 22:28:00 raspberrypi evcc[7585]: [ocpp  ] TRACE 2023/07/02 22:28:00 received JSON message from goe123456: [3,"2558598256",{"status":"Rejected"}]
`

No matter if dummy card is activate with id 'evcc' or deactivated. Generell authentification is disabled.

**Comment by andig** [comment]
Formatting the logs would make them readable ;)

**Comment by slev1n** [comment]
@andig thx for the hint. I uploaded the log file

**Comment by 0xFEEDC0DE64** [comment]
at the end of the log I see a Rejected response to a RemoteStartTransaction message,

what is the status of the charger in that moment? has another transaction already been started?

**Comment by slev1n** [comment]
No other transaction, clean reboot of the charger and evcc.

**Comment by slev1n** [comment]
I updated and restartet charger and pi and now it works:). 
Just run into another open issue [OCPP: Current limit ignored when suspended charging session is resumed](https://github.com/goecharger/go-eCharger-API-v2/issues/155)
