### ISSUE TITLE
Abfrage der Energie der 10 RFID Chips per Modbus.

### ISSUE THREAD

**Issue by alealdata** [goecharger/go-eCharger-API-v2#128]
Jeweils ein Register pro RFID erspart das http Polling

**Comment by alealdata** [comment]
Ja und das hab ich in der Loxone bereits umgesetzt!
Das wär super wenn es beim nächsten Update dabei ist.

**Comment by 0xFEEDC0DE64** [comment]
die modbus register sind jetzt implementiert, heißt beim nächsten firmware update sind die dabei, ich dokumentier die noch schnell auf github

**Comment by 0xFEEDC0DE64** [comment]
firmware release 055.6 von heute beinhaltet diesen change jetzt
