### ISSUE TITLE
`bac` und `sdp` sind keine Booleans mehr

### ISSUE THREAD

**Issue by syssi** [goecharger/go-eCharger-API-v2#130]
Vgl. https://github.com/syssi/homeassistant-goecharger-mqtt/issues/88

Ich habe die Hoffnung, dass diese Änderung der API versehentlich passiert ist und wir wieder zurück zu den boolschen Werte können.

**Comment by 0xFEEDC0DE64** [comment]
Die requirements an die Einstellung sind gewachsen, 0 und 1 sollten so wie früher false und true verhalten, und zwei neue Optionen wurden eingeführt:

| api key | type | description |
| - | - | - |
| bac | uint8_t | Button allow Current change (0=AlwaysLock, 1=LockWhenCarIsConnected, 2=LockWhenCarIsCharging, 3=NeverLock) |
| sdp | uint8_t | Button Allow Force change (0=AlwaysLock, 1=LockWhenCarIsConnected, 2=LockWhenCarIsCharging, 3=NeverLock) |

sorry für's Nicht-Dokumentieren, ich ziehs nachher gleich nach
