### ISSUE TITLE
Passwort setzen funktioniert nicht

### ISSUE THREAD

**Issue by JochenFriedrich** [goecharger/go-eCharger-API-v2#15]
Wenn man mit API Key pass ein neues APP Passwort setzt, egal ob über HTTP oder MQTT, funktioniert dieses in der APP nicht. Komplett löschen geht aber.

Firmware 051.4

**Comment by peterpoetzi** [comment]
Um das Passwort zu setzen muss es erst mit PBKDF gehasht werden. Da das relativ kompliziert ist, werden wir die Möglichkeit das Passwort über die API zu setzen ausbauen
