### ISSUE TITLE
How to Stop Charging via APIv2?

### ISSUE THREAD

**Issue by nicoketzer** [goecharger/go-eCharger-API-v2#153]
Hello all,
I am currently migrating the OpenEMS implementation from the Go-E APIv1 to the Go-E APIv2 (for the newer hardware versions). 

I have encountered some problems in this process, but so far I have always been able to solve them.

Currently I fail because I can no longer end the charging process (once started) via the API.

In the APIv1, the value alw was set to "0" and everything was good. In APIv2, however, the value alw is read-only and can therefore no longer be used. Setting amp to -1 or 0 or null [...] always returns a "500 Internal Server Error" whose content is a json that is structured as follows:
{
    "amp": "amp: failed: value must be uint8_t (-1)"
}
or
{
    "amp": "amp: failed: Value 0 exceeds range 6 to 32 (0)"
}
or
{
    "amp": "amp: failed: null not allowed (null)"
}

After reading the APIv2 documentation several times, I don't know how to stop the charging process via the REST-API. Can someone help me here?

**Comment by herbert131** [comment]
I set current (amp)and phase (psm) and than start charging with frc =2
STOP with frc = 1
