### ISSUE TITLE
PV-Überschusseinstellungen vom hinterlegten Fahrzeug übernehmen

### ISSUE THREAD

**Issue by Micha982** [goecharger/go-eCharger-API-v2#164]
Hallo, 

wäre es möglich, die PV-Überschusseinstellungen in die Fahrzeugkonfiguration zu übernehmen? Sonst muss man bei jedem Fahrzeugwechsel an verschiedenen Untermenüs die Einstellungen anpassen.

Ebenso wäre es hilfreich, globale Daten wie beispielsweise die Fahrzeugdaten übergreifend zu synchronisieren. Bei 3 Boxen verliert man sonst schnell den Überblick.

**Comment by erxbout** [comment]
Hallo,

Da wir nicht wissen können welches Fahrzeug angeschlossen wird, können wir hier leider nichts machen..
Die Kommunikation mit dem Fahrzeug läuft Analog und hier wird nur der maximale Ladestrom ausgetauscht und ob geladen werden darf oder nicht..
