### ISSUE TITLE
Cloud Zugang

### ISSUE THREAD

**Issue by Newan** [goecharger/go-eCharger-API-v2#18]
Hallo,

ist es Möglich mit Hardware v3 und der APi v2 auf die Cloud zuzugreifen. Inder app kann man den Zugriff zulassen, aber keine Doku wie ein Auslesen über das internet möglich ist?

**Comment by peterpoetzi** [comment]
Die Cloud API für die V3 ist derzeit in Entwicklung

**Comment by peterpoetzi** [comment]
Die Cloud API ist hier dokumentiert: https://github.com/goecharger/go-eCharger-API-v2/blob/main/cloudapi-de.md
