### ISSUE TITLE
no connection to mqtt server with username and password

### ISSUE THREAD

**Issue by christiandulle** [goecharger/go-eCharger-API-v2#184]
my home assistant mqtt needs a username and password. in go-e app there are no fields to setup. so i tried it within the link

user:password@mymqttserver.com:1883

but i dont get a connection. does anyone have a solution for that?

kind regards
christian

**Comment by povlhp** [comment]
My URL is `mqtt://user:password@server.lan:1883` - it works flawlessly
Just be sure that your password does not conflict with http stuff like / + ? <> or % - I use numbers, digits and only a very small subset of special characters.

**Comment by erxbout** [comment]
Is this still relevant?

Seems like the URL needs to be specified starting with mqtt:// like @povlhp already mentioned..

**Comment by erxbout** [comment]
I will close this issue since the url format as previously stated is

```
mqtt://user:password@server.lan:1883
```
