### ISSUE TITLE
Enable/Disable Next-Trip and Eco charging via API

### ISSUE THREAD

**Issue by dns13** [goecharger/go-eCharger-API-v2#189]
Is it possible to disable next trip and eco charging via the API? I don't see any endpoints for that, only read only infos for next trip. Or is it possible to force charging temporary if car is connected and authenticated?

When I request everything without a filter set theres many undocumented keys returned. I also tried to update the setting via the app and check which keys changed, but without any obvious non sensor like data changes.

Maybe there is another way to solve what I want to achieve with some script running on an external device:
My car has a scheduled departure setting where it heats up the battery and passenger cabin starting 30 minutes prior to a preconfigured time but that only happens if it is plugged in and allowed to charge.
I want to use next-trip mode to charge up the car with lowest cost possible over night BUT it should also force load in a defined time span. So it's not AND to allow charging like I can do with the internal scheduling of the charger I want an OR to charge whether the next-trip mode allows charging or it is inside bespoke timespan.
I would also take an improved next-trip mode that takes this 30 minutes into account and calculates around that, but just using next-trip as normal and enable charging in my 30 minutes slot would suffice for me.

At the moment I'm manually disabling next-trip in the morning via the app so there should be an (internal) endpoint for that?

**Comment by 0xFEEDC0DE64** [comment]
you can use the api key lmo

set lmo=3 for default charging without most of the smartness
set lmo=4 for eco mode
set lmo=5 for next trip charging

**Comment by dns13** [comment]
Thank you!
