### ISSUE TITLE
RFID api fehlt

### ISSUE THREAD

**Issue by andig** [goecharger/go-eCharger-API-v2#19]

**Comment by peterpoetzi** [comment]
Es gibt dem Parameter trx wo steht mit welcher Karte der Ladevorgang freigeschalten wurde

**Comment by andig** [comment]
Und wo ist die Dokumentation der Karten? In den API Keys gibt es keinen entsprechend dokumentierten Schlüssel.

**Comment by peterpoetzi** [comment]
Es gibt den API key cards

**Comment by andig** [comment]
Wo ist der dokumentiert? In https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-de.md finde ich nichts. Weder den Begriff, noch woraus die Inhalte bestehen. Vielleicht könntest Du das Issue wieder öffnen bis es eine Dokumentation gibt? Vielen Dank!
