### ISSUE TITLE
change minChargingCurrent via API

### ISSUE THREAD

**Issue by mf76130** [goecharger/go-eCharger-API-v2#205]
I have 2 cars, one can start charging at 6A and the other only at 12A, it would be very comfortable if i could change the minChargingCurrent (LOM) via API.

**Comment by erxbout** [comment]
This is implemented by the api-key "mca"

**Comment by mf76130** [comment]
yes, thanks, forgot to add that info here when i got it
her my examples for rest commands:

rest_command:
  mindest_ladestrom_12a:
    url: http://192.168.0.91/api/set?mca=12
  mindest_ladestrom_6a:
    url: http://192.168.0.91/api/set?mca=6

**Comment by erxbout** [comment]
Nice, glad that it works and your issue is solved ;)
