### ISSUE TITLE
New ChargingReason modelStatus code 28 introduced in Fronius Wattpilot firmware 40.7

### ISSUE THREAD

**Issue by pbrooks29** [goecharger/go-eCharger-API-v2#214]
Using the Fronius Wattpilot integration which is based on this project, getting an error due to an unhandled status code 28 in ChargingReason.

'Reason why we allow charging or not right now - values are listed at: https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-de.md -> modelStatus'.
Looking at the Solar.Wattpilot app, this code is associated with the message "**Charging Stopped by OCPP backend**" on the WattPilot app.
Which I suspect is newly added in the Fronius Wattpilot 40.7 firmware and wasn't there when this 'goecharger' code was written.
The table in 'apikeys-de.md' or 'apikeys-en.md' for 'modelStatus' stops at code 24.
Please add entry for new modelStatus code 28:

NotChargingBecauseOCPPBackend=28

(I haven't uncovered any of the middle codes 25, 26 or 27 yet) 
Thanks.

**Comment by 0xFEEDC0DE64** [comment]
I have updated the list on github according to our firmware source code.
