### ISSUE TITLE
Android App: InApp Notification settings (for charger events) have no effect

### ISSUE THREAD

**Issue by marq24** [goecharger/go-eCharger-API-v2#230]
The current Android App allow to configure the Events when the App should send an notification (e.g. start loading, end loading, loading paused). Unfortunately these settings does not have a effect at all. No matter what I configure (disable), I always receive notifications for all events. The only solution right now is to disable Notifications for the App in general in Android OS.

**Comment by erxbout** [comment]
Other customers also noticed this.. App team is informed and they are working on it!

**Comment by erxbout** [comment]
Should be fixed now with app version 4.4.1
If not please let us know
