### ISSUE TITLE
Issue with OCPP and ChangeConfiguration: wrong key for MeterValuesSampleInterval

### ISSUE THREAD

**Issue by mincequi** [goecharger/go-eCharger-API-v2#240]
Hi there,

i noticed a bug in the OCPP implementation. Apparently you use MeterValueSampleInterval instead of MeterValue**s**SampleInterval. So, i get a {"status":"NotSupported"} when trying to change that interval using the ChangeConfiguration call.
When I try MeterValueSampleInterval (as you implemented it), i get a {"status":"Accepted"}. However, MeterValues are not sent by the ChargePoint.

Hope that helps.

**Comment by 0xFEEDC0DE64** [comment]
I cannot find MeterValuesSampleInterval anywhere in the ocpp spec and only MeterValueSampleInterval is documented on many pages. Where did you get your OCPP docs?
