### ISSUE TITLE
V 56.8 MQTT sends Homeassistant although HA is switched off

### ISSUE THREAD

**Issue by juergen852** [goecharger/go-eCharger-API-v2#246]
Firmware 56.8 sends homeassistant topic + data altough "MQTT homeassistant aktiviert" is switched off in the app .

Checked on my 10 chargers...

**Comment by CommanderRedYT** [comment]
Was it turned on at any given time? If so, you will have to manually delete the topics from your mqtt server because the retain flag is set.

**Comment by erxbout** [comment]
This is the same problem as in #231

**Comment by juergen852** [comment]
@CommanderRedYT 
It might have been turned on on 1 or 2 chargers for testing, but not on all.
I deleted all messages on my server.
All chargers re-appear with homematic, although not activated in e-go app.

![grafik](https://github.com/user-attachments/assets/5cce0c67-7261-4045-af82-83d9b6e432f6)

**Comment by 0xFEEDC0DE64** [comment]
It was fixed 2 or 3 beta versions in the past already
