### ISSUE TITLE
Festlegen der Autotype vor Ladestart ("Aufweck"-Feature)

### ISSUE THREAD

**Issue by chk2902** [goecharger/go-eCharger-API-v2#28]
Wenn ein Kunde das Auto am Lader wechselt und dann per App der Autotyp (wegen des "Aufweckens") eingestellt werden soll, wie geschieht das? Gleichzeitig mit Ladestart, ...? Im Prinzip das Gleiche wie bei https://github.com/goecharger/go-eCharger-API-v2/issues/27.

**Comment by peterpoetzi** [comment]
Den Autotyp in der App kann man zu jedem Zeitpunkt einstellen. Beim Ladestart oder einer Ladeunterbrechung wird dann die jeweils passende Aktion ausgeführt

**Comment by chk2902** [comment]
@peterpoetzi und welche Typen gibt es (derzeit)?
