### ISSUE TITLE
Api V2: was verbirgt sich hinter spl3 (float, threePhaseSwitchLevel)

### ISSUE THREAD

**Issue by fu-zhou** [goecharger/go-eCharger-API-v2#31]
Hallo, hatte gehofft, dass man mit spl3 von 1- auf 3 Phasen und umgedreht umschalten kann, dazu passt "float" aber nicht. Hat jemand Ahnung, was mit dem Key gesteuert wird?

**Comment by peterpoetzi** [comment]
Mit spl3 wird man mit dem kommenden go-e Controller einstellen können, bei welcher Überschussleistung eine Umschaltung von 1 auf 3 Phasen, bzw. umgekehrt vorgenommen wird. Derzeit wird dieser Parameter von der Firmware nicht ausgewertet.
