### ISSUE TITLE
MQTT protocol 3.1 vs 3.1.1

### ISSUE THREAD

**Issue by one4many** [goecharger/go-eCharger-API-v2#34]
API v1 supported MQTT version 3.1.1 and this one only 3.1 which creates a whole lot of issues in the software I use.
Is there a particular reason why? Or would be possible to upgrade to 3.1.1 (which was the default anyway)?
Even better, let the user decide which version should be used in the advanced settings.

**Comment by 0xFEEDC0DE64** [comment]
Ab dem nächsten Firmware Release wird MQTT Protokoll Version 3.1.1 verwendet.

**Comment by one4many** [comment]
@0xFEEDC0DE64 ist die neue Firmware schon veröffentlicht?

**Comment by 0xFEEDC0DE64** [comment]
jawoll, ist schon draussen. Einfach auf die neueste Version updaten, falls noch nicht gemacht.
