### ISSUE TITLE
Die API zum Setzen von "upo" ist fehlerhaft und meldet einen fehlenden setter.

### ISSUE THREAD

**Issue by chk2902** [goecharger/go-eCharger-API-v2#40]
Ich finde den Key in der HTTP-Doku nicht.

**Comment by chk2902** [comment]
klingt gut, danke.

**Comment by peterpoetzi** [comment]
Tatsächlich ist upo richtig. Allerdings gibt es intern zwei upo Kommandos, eines das true / false nimmt, und eines das integer 1 / 0 nimmt. Die Firmware versucht beide auszuführen und das mit integer input liefert immer einen Fehler. Wir werden das in der nächsten Firmware version beheben.

**Comment by 0xFEEDC0DE64** [comment]
ist mit neuer firmware 052 schon gefixt.
