### ISSUE TITLE
MQTT User und Passwort

### ISSUE THREAD

**Issue by pschyrembel258** [goecharger/go-eCharger-API-v2#42]
Hallo, 
wie kann ich den User und das Passwort von meinem Broker in der App eingeben? Ich finde leider keine Möglichkeit.

Vielen Dank 

Daniel

**Comment by copacetic82** [comment]
bei mir funktioniert das wenn ich die URL in folgendem format eingebe: mqtt://username:passwort@X.X.X.X:1883

**Comment by pschyrembel258** [comment]
Hat funktioniert, danke.
