### ISSUE TITLE
MQTT Topic entspricht ggf. nicht üblichen Standards

### ISSUE THREAD

**Issue by ako-3004** [goecharger/go-eCharger-API-v2#44]
Im MQTT Explorer ist mir aufgefallen, dass das zugewiesene Topic nicht ganz dem normalen Standard entspricht.
Es startet mit einem "/". Alle anderen Topics die mir bisher begegnet sind starten mit einem String.
Es scheint keine Probleme dadurch zu geben, ich will das aber nicht ausschliessen.
Es wäre vermutlich sinnvoll das Topic des go-e anpassen zu können, somit vorne einen String setzen zu können.

![go-e-issue](https://user-images.githubusercontent.com/46303527/142775334-4aad4a49-ea04-47ae-8144-74fb74f7c331.png)
.

**Comment by 0xFEEDC0DE64** [comment]
Ich fürchte, dass wenn wir den `/` am Anfang nun entfernen, werden ganz viele vorhandene Integrationen nicht mehr funktionieren und das wird zu Problemen führen. `/` am Anfang ist ja per Standard explizit erlaubt.

**Comment by ako-3004** [comment]
Ich denke wenn ihr Euch das als Task hinterlegt das Topic langfristig für den User einstellbar zu machen, dann wäre das nicht schlecht. Aktuell sehe ich auch keinen Handlungsbedarf, wollte Euch den Sachverhalt aber mal melden.

**Comment by nean-and-i** [comment]
Hallo,

bitte um Korrektur, es scheint ein zusätzlich leeres topic reingerutscht worden sein vmtl. durch doppel  "//"
Das dürfte ein Fehler sein, sowas macht keine einzige mqtt implementation.

![image](https://user-images.githubusercontent.com/1310469/144841511-20bad3ef-47c5-4b1f-837b-308f9a1778f8.png)

Vielen Dank.

**Comment by nean-and-i** [comment]
> Ich fürchte, dass wenn wir den `/` am Anfang nun entfernen, werden ganz viele vorhandene Integrationen nicht mehr funktionieren und das wird zu Problemen führen. `/` am Anfang ist ja per Standard explizit erlaubt.

leading / macht man nicht bei MQTT, man generiert dadurch nur mehr Probleme, wenn man zero value root topics erstellt.

Das ist schwerstens verpönt in der MQTT community -> Don’t use a leading slash (e.g. /mytopics ) to start your topic tree

thnx

**Comment by peterpoetzi** [comment]
Wir werden mit Firmware 052.2 die Möglichkeit anbieten den Prefix für die mqtt topics setzen zu können.

Standardmäßig ist der Prefix exemplarisch mit der Seriennummer 123456:
"`/go-eCharger/123456/`". 

Das kann man anpassen auf "`go-eCharger/123456/`" wenn man nur den führenden / entfernen möchte, auf "`meineHomeAutomation/garageLinks/`", oder einfach auf einen leeren String "` `".

Der API parameter für mqtt topic prefix heißt `mtp`. Die Firmware 052.2 wird spätestens nächste Woche released, die App mit dem dazugehörigen Eingabefeld, kann eventuell etwas länger dauert, aber man kann den prefix ja auch über die API direkt setzen.

**Comment by nean-and-i** [comment]
Vielen Dank.

Wird man über die go-e APP (iOS/Android) darauf einen Einfluss nehmen können?

Es wäre aber sinnvoller wenn per default der Präfix entfernt wird , damit es danach dem Standard folgt -> `go-eCharger/123456/` 

Das sollte eigentlich keine nennenswerten Probleme mit sich bringen, einmal eine bestehende integration gemäß standard umkonfigurieren (`/` entfernen), es gehen ja keine Daten dadurch verloren. (z.b. breaking changes passieren ständig bei homeassistant)

**Comment by erxbout** [comment]
Dieses issue ist schon ziemlich alt, das topic ist mittlerweile in der App änderbar daher würde ich dieses issue schließen!
