### ISSUE TITLE
Modbus API v2

### ISSUE THREAD

**Issue by YoungCereal** [goecharger/go-eCharger-API-v2#45]
Hat sich etwas Grundlegendes an der ModbusAPI für die v3 goecharger gändert ?
Da ich Probleme habe eine Verbindung mit meinem goecharger ( wurde ausgetauscht davor keine Probleme) mehr bekomme ?

Gruß
Michael

**Comment by 0xFEEDC0DE64** [comment]
Ist modbus in der App aufgedreht worden? Scheitert der Aufbau der TCP Verbindung? Wird eine modbus-Anfrage nicht oder mit einem Fehler beantwortet?
