### ISSUE TITLE
Anzeigen welches Auto gerade lädt ?

### ISSUE THREAD

**Issue by lyncker** [goecharger/go-eCharger-API-v2#46]
Hallo, ich versuche über die API etwas über das aktuell ladende Auto herauszufinden... 
Derzeit nutze ich keine RFID Chips und will das bis auf weiteres auch nicht tun, aber es wäre hilfreich , wenn ich für das aktuell ladende Auto einen Namen oder eine SerialID oder sonstwas uniques finden könnte .. in der Doku hab ich nichts gesehen... gibt es etwas ?

**Comment by peterpoetzi** [comment]
Derzeit ist es leider nicht möglich zu erkennen welches Auto gerade lädt. Die Kommunikation mit dem Auto läuft nur über ein PWM signal mit analogen Spannungspegeln, es wird leider keine Seriennummer oder ähnliches übermittelt
