### ISSUE TITLE
MQTT - kein syntax check in der APP /  mqtt passwort ungeschützt

### ISSUE THREAD

**Issue by nean-and-i** [goecharger/go-eCharger-API-v2#50]
Nachdem es für die APP(s) kein github issue gibt, darf ich folgende Anliegen im Zusammenhang mit MQTT hier melden?

# mqtt - Bug request APP (iOS)

Zur Zeit ist es so, sobald man in der APP, MQTT aktiviert und im MQTT URL Feld einen Syntaxfehler erzeugt oder das URL Feld leer lässt, läuft der go-e in einem reboot loop und man lernt wie praktisch die Resetkarte sein kann.

# mqtt - Feature request APP(iOS): 

Eigene Eingabefelder für MQTT Benutzer und maskiertes Eingabefeld für Password, damit die MQTT Zugangsberechtigungen geschützt bleiben.

**Comment by peterpoetzi** [comment]
Ich kann den Fehler mit dem Bootloop bei leerer bzw. syntaktisch falscher URL bestätigen. Wir werden in wenigen Minuten eine Firmware Update veröffentlichen das den Fehler behebt.

Bezüglich den Eingabefehlern für Benutzer und Passwort nehmen wir den Wunsch gerne auf, derzeit gibt es aber keine Timeline dafür.

**Comment by peterpoetzi** [comment]
Die neue Firmware wurde released
