### ISSUE TITLE
New Android App contains Google Firebase Messaging

### ISSUE THREAD

**Issue by JochenFriedrich** [goecharger/go-eCharger-API-v2#51]
562 tested signatures on 11551 classes
(6481787)

Google Firebase Analytics
²?Sentry

*Google Firebase Analytics
5com.google.firebase.analytics.

*²?Sentry
328io.sentry

**Comment by peterpoetzi** [comment]
The new app uses firebase messaging for the push notifications feature, but does not contain firebase analytics. So the signature is probably mislabeled.

**Comment by JochenFriedrich** [comment]
Google Firebase Analytics is enabled by default if Firebase is being used.

See
https://github.com/nextcloud/android/issues/2657

**Comment by peterpoetzi** [comment]
I could not find any hints that analytics are sent even when disabled (and they are disable in the go-e app)
