### ISSUE TITLE
Restart Charger not working (rst=1)

### ISSUE THREAD

**Issue by SloppolS** [goecharger/go-eCharger-API-v2#53]
Hi,

I need to restart the go-e charger, to start charging the new ZOE (R135). 
According to the support, this is possible via the API with `rst=1 `command.

But thats not working for me. 

With typing `http://192.168.2.x/api/set?rst=1` in browser, I received `"null"`

All other commands like` http://192.168.2.x/api/status?` or changing phases with `http://192.168.2.x/api/set?psm=1` are working great.

My Charger is v3 and I activated HTTP API v2.

What can cause this issue?

**Comment by 0xFEEDC0DE64** [comment]
The new api key rst should be available since version 53.0

**Comment by SloppolS** [comment]
Thanks a lot.

With 53.0 Beta rst is working fine!
