### ISSUE TITLE
WLAN Name of charger V3 does not appear 

### ISSUE THREAD

**Issue by ECOM-Engineering** [goecharger/go-eCharger-API-v2#56]
It is difficult to find the new V3 Charger in the WLAN because its name does not appear.
Scanning Wifi on Win10:
Charger V3 appears as "pc-485" with manufacturer "espressif Inc" instead of the "friendly name" defined in key "fna". 

(In V2 the  name "go-eCharger_xxxxxx"  appeared.)

**Comment by 0xFEEDC0DE64** [comment]
The manufacturer is correct, but the hostname "pc-485" is not sent from the charger, maybe your DHCP server caches this name from another machine on the network?
This is how it looks on our DHCP server, the hostname is not the friendly name, but a constant prefix with your serial number:

![image](https://user-images.githubusercontent.com/10342708/149788247-a0f7a735-177b-482b-b6f1-d8ed729a94fc.png)
