### ISSUE TITLE
API Key für "Geplanter Ladevorgang" fehlt

### ISSUE THREAD

**Issue by dako0815** [goecharger/go-eCharger-API-v2#61]
In der App kann man unter "Geplanter Ladevorgang" verschiedene Einstellungen tätigen. Für die Werte für "Lademenge" und "Fertig um" gibt es aktuell keinen API Key. Wird hierfür noch was kommen?
Ich würde nämlich gerne die Awattar-Logik vom go-e nutzen und nur die beiden Werte durch den iO Broker befüllen...

![Screenshot_20220204-090049](https://user-images.githubusercontent.com/78207468/152494524-01918c89-f026-4b6a-bbd8-17f4e4743860.jpg)

**Comment by arboeh** [comment]
Für die Funktion muss der Geplante Ladevorgang auf der Startseite der App aktiviert sein. Key ist "lmo".
Mit dem Key "ate" kann man die "geplante" Energiemenge festlegen, mit "att" die Endzeit. Verwende ich in Home-Assistant und funktioniert bestens.

**Comment by dako0815** [comment]
Ok perfekt. Vielen Dank. Das hatte ich leider nicht gefunden bzw. falsch interpretiert...
