### ISSUE TITLE
MQTT Topic beginnt mit /

### ISSUE THREAD

**Issue by digidax** [goecharger/go-eCharger-API-v2#84]
Wäre es möglich, dass die MQTT Topic NICHT mit / beginnt, sondern direkt mit go-eCharger/123456

Ist im MQTT Explorer schöner go-eCharger gleich in der Root Topic zu sehen anstatt ein leeres Feld:
![grafik](https://user-images.githubusercontent.com/5276312/182114697-3abd7892-3890-4138-b902-ee596f990734.png)
![grafik](https://user-images.githubusercontent.com/5276312/182114785-a6add6c1-9136-48a4-88fd-3e5f1567ac3a.png)

**Comment by 0xFEEDC0DE64** [comment]
als kurzfristigen work-around:
api key "mtp", type string, "mqtt topic prefix, set to null to reset to default again"

**Comment by copacetic82** [comment]
Hat sich dieses Verhalten in der neusten version 054.6 Beta geädnert, ohne es in den release notes erwöhnt wurde? Bei mir waren die topics nach dem upgrade auf einer einer anderen ebene, und diverse sensoren funktionierten dadurch nicht. Hab vorerst ein rollback auf 054.3 gemacht. Wird das auch in die nächste non-beta version übernommen? 

Siehe vergleich: 
![image](https://user-images.githubusercontent.com/45660618/192537606-dbd080e6-6f67-4e5c-8065-aee408d9b436.png)

**Comment by arboeh** [comment]
Kann ich bestätigen und ich habe mir in den letzten Stunden nen Wolf gesucht, weil ich heute eine neue Instanz aufgesetzt habe... :-|

**Comment by copacetic82** [comment]
> Kann ich bestätigen und ich habe mir in den letzten Stunden nen Wolf gesucht, weil ich heute eine neue Instanz aufgesetzt habe... :-|

Ging mir ähnlich, konnte es aber zum glück recht schnell eingrenzen. Wäre cool gewesen wenns in den release notes stehen würde :/

**Comment by syssi** [comment]
Same here:

```
-/go-eCharger/072246/fhz 49.754
+go-eCharger/072246/fhz 49.754
```

**Comment by copacetic82** [comment]
fixed in 054.7 Beta

**Comment by digidax** [comment]
The forward slash (/) is used to separate each level within a topic tree.
Focus is the separation not the beginning:
[http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718106](url)

MQTT Best practices
Never use a leading forward slash

A leading forward slash is permitted in MQTT. For example, /myhome/groundfloor/livingroom. However, the leading forward slash introduces an unnecessary topic level with a zero character at the front. The zero does not provide any benefit and often leads to confusion.
[https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/](url)

**Comment by fu-zhou** [comment]
in der 54.7 hat sich irgendwie auch verändert, wie der go-e charger seine Datenpunkte über MQTT veröffentlicht - s. https://github.com/goecharger/go-eCharger-API-v2/issues/89#issuecomment-1272274910

**Comment by 0xFEEDC0DE64** [comment]
ich wollte eigentlich nur für neue mqtt-installationen endlich den / zu beginn los werden, in der ersten beta hat's aber den default auch für bestehende mqtt-user mit verdreht, mit dem nächsten beta update sollte es jetzt so sein, dass wenn mqtt schon aufgedreht war, er den führenden / behält und für neue mqtt user per default nur ohne / vorschlägt und man kann manuell in der app den mqtt topic prefix selber nach wunsch verändern.

**Comment by erxbout** [comment]
duplicate of https://github.com/goecharger/go-eCharger-API-v2/issues/44

Ich schließe dieses issue, da das topic in der app inzwischen einstellbar ist und der default ohne leading "/" kommt
