### ISSUE TITLE
firmware 054 regression test problem: setting car type (ct) does not work by the httpv2 api any more 

### ISSUE THREAD

**Issue by chk2902** [goecharger/go-eCharger-API-v2#86]
`Internal Server ErrorServer-Fehler: {"acs":true,"ct":"ct: tried to set api key which is not allowed from api (renaultZoe)"}`

It did work with 0.53.1, I just downgraded.

{"acs":true,"ct":true}

**Please do allow this command again as a lot of customers depend on it.**

**Comment by 0xFEEDC0DE64** [comment]
Sollte seit September wieder möglich sein, ich habe das "FromApi" und "ToApi" flag für den api key wieder aufgedreht (dürfte bei einem refactoring verloren gegangen sein)
