### ISSUE TITLE
054.7 Final: MQTT Objekte haben kein "set" mehr

### ISSUE THREAD

**Issue by fu-zhou** [goecharger/go-eCharger-API-v2#99]
Ich nutzte auch den MQTT Adapter in iobroker und steuere z.B. Ladestrom und Anzahl Phasen über ein blockly Skript (amp + psm). Bei der 54.7 stehen alle Werte im "root" und die Werte können nicht mehr über das Skript geschrieben werden, weil das Unter-Objekt "set" in den schreibbaren Objekten fehlt:

54.7 Objektbaum:
![image](https://user-images.githubusercontent.com/11984960/194699933-6e9a1e79-0abe-484b-be48-15daaeb7abab.png)

54.3 Objektbaum:
![image](https://user-images.githubusercontent.com/11984960/194700134-a0efae87-141a-42f9-ab50-2e387444bf9e.png)

Liegt das am MQTT Adapter (MQTT Broker/Client V 4.0.7) vom iobroker oder an der Firmware 54.7? Die Kombination aus MQTT Adapter und FW 54.3 funktioniert wieder nach Dowgrade 54.7 -> 54.3

**Comment by 0xFEEDC0DE64** [comment]
In einer der letzten Versionen habe ich eingezogen, dass der Charger auch endlich auf ungültige Schreib-Anfragen antwortet.
Der Charger subscribed jetzt nicht mehr für 100 api keys einzeln (was kurzzeitig sehr viel RAM frisst), sondern subscribed nur mehr einmal auf ein wildcard topic.

Ist der mqtt server im iobroker großartig anders als der von mosquitto? Lässt sich der gescreenshottete test irgendwie nachstellen?

![image](https://user-images.githubusercontent.com/10342708/199772760-9caff4bd-6a93-4fa1-95b0-eeec61e894d2.png)

**Comment by fu-zhou** [comment]
Da bin ich zu sehr Anwender, als Entwickler... Der iobroker mqtt Server schreibt die Werte von den Clients in die Objektdatenbank (s. Screenshots oben), diese Objekte werden dann in den Skripten adressiert. Ein Terminal-Fenster gibt es da nicht und auch nicht die Möglichkeit (für mich mit meinen Fähigkeiten), die Objekte mit einem Parameter zu ergänzen (z.B. amp**/set**). 

Was muss denn der Server machen/ können, um bei der aktuellen Firmware wieder den vollen Umfang einzulesen? Vielleicht kann ich das dann beim iobroker mqtt Adapter Entwickler hier in Github https://github.com/ioBroker/ioBroker.mqtt einspeisen?

Der Konfigurationsdialog vom Adapter sieht so aus:
![image](https://user-images.githubusercontent.com/11984960/199791166-5bdd178a-8e4c-4df1-9fb4-950a9bcfb645.png)
Erkennst du da eine Option, die das macht, was ich brauche? Ich habe schon ein bischen rumprobiert, bin aber nicht zum gewünschten Ergebnis gekommen

**Comment by tops4u** [comment]
Ich habe das gleiche Problem. 

Beim Connect sieht es so aus, als würde die Subscription funktionieren:

`Client [go-echarger_xxxxxx] subscribes on "go-eCharger/xxxxxx/+/set" with regex /mqtt\.0\.go-eCharger\.xxxxxx\.[^.]*\.set/`
 `Client [go-echarger_xxxxxx] subscribes on "go-eCharger/xxxxxx/+/set" with regex /go-eCharger\.xxxxxx\.[^.]*\.set/`

Wenn ich dann allerdings in IOBroker das Set Objekt ändere (Objekt ID: mqtt.0.go-eCharger.xxxxxx.amp.set) dann ändert sich da gar nichts mehr. 

Ich denke der Charger verwendet diese Regex für die Subscription: _go-eCharger\.xxxxxx\.[^.]*\.set/_
Die zieht allerdings beim MQTT Adpater auf IOBroker nicht. Diese hier würde gehen: _go-eCharger\.xxxxxx\.[a-zA-Z0-9]*\.set_

**Comment by tops4u** [comment]
Abgesehen davon zeigt mir die Go.E App die Changelogs für 54.8 mit Bugfixes für MQTT an, jedoch steht oben nur bis 54.7 als Installierbar zur Auswahl... 

Grundsätzlich würde ich lieber Modbus TCP verwenden, da gibt es jedoch bisher keine Möglichkeiten die Phasen Anzahl zu schalten.

**Comment by fu-zhou** [comment]
> Abgesehen davon zeigt mir die Go.E App die Changelogs für 54.8 mit Bugfixes für MQTT an, jedoch steht oben nur bis 54.7 als Installierbar zur Auswahl...
> 
> Grundsätzlich würde ich lieber Modbus TCP verwenden, da gibt es jedoch bisher keine Möglichkeiten die Phasen Anzahl zu schalten.

Ist bei mir auch so, habe gedacht, dass sich die 54.8 vielleicht versteckt und mal das Update laufen lassen - dann wird dir 54.7 installiert. Warten wir mal ab...

**Comment by tops4u** [comment]
> Warum würdest du Modbus TCP vorziehen?

Weil MQTT mir viel zu viel Zeugs liefert. Bei Modbus TCP habe ich besser Kontrolle über was ich haben will, wie es heissen soll und wie oft es aktualisiert wird. Allerdings ist die Konfig etwas "schmerzhafter". Da ich die Übung allerdings bereits für meine PV-Wechselrichter gemacht habe, weiss ich nun wie es geht.

**Comment by fu-zhou** [comment]
Ist ein Argument. Hast du nen SolarEdge WR? Hättest du Lust, mal deine aktuelle iobroker Modbus-Adapter Konfiguration zu posten (für WR und für den goE Charger)? Oder hast du das schon mal irgendwo gezeigt, z.B. im iobroker Forum?

Danke vorab...

**Comment by tops4u** [comment]
Mit der aktuellen Version (54.9) funktioniert bei mir wieder alles.

**Comment by fu-zhou** [comment]
bei der 54.9 funktioniert es bei mir nur, wenn ich den Objekt-Baum beibehalte, wie er unter der 54.3 angelegt wurde (also "set" und "result" unterhalb von "amp"). Wenn ich den Objektbaum lösche und bei der ersten MQTT-Verbindung mit der 54.9 wieder anlegen lasse, habe ich das Problem wie oben beschrieben. Wie sieht das "funktioniert" unter 54.9 bei dir aus?

**Comment by tops4u** [comment]
> bei der 54.9 funktioniert es bei mir nur, wenn ich den Objekt-Baum beibehalte, wie er unter der 54.3 angelegt wurde (also "set" und "result" unterhalb von "amp"). 

Ja das ist insofern zu erwarten, da GO.E nun eben nicht mehr eine Subscription für alle Objekte macht, sondern ein Wildcard. Somit kann der Broker die möglichen SET Objekte ja gar nicht kennen. Um also einen Wert zu schreiben, musst DU explizit ein SET Objekt unterhalb dem angezeigten Objekt anlegen in IOBroker.

**Comment by fu-zhou** [comment]
Hmh... wie lege ich das an? Mit einem Script? Mit CreateState unter Blockly wird das Objekt allerdings in der Javascript-Instanz angelegt, nicht unter MQTT... Der Objektbaum lässt mich unter einem State keinen weiteren State mehr anlegen, obwohl "amp" in der 54.3 ein State ist (allerdings als Ordner dargestellt) mit den unterlagerten States "set" und "result".
Insofern wäre mit Modbus mittlerweile auch lieber, wenn die API schon voll umfänglich integriert wäre (Phasenumschaltung etc.)

**Comment by fu-zhou** [comment]
Hab's mit dem ioBroker Forum gelöst: Auf das Objekt "go-eCharger" gehen, dort einen neuen Datenpunkt anlegen:
"number" amp.set
"string" amp.result

und schon passt's wieder...
